class Scryfall:
    def __init__(self, config):
        self.base_url = config.get('base_url', fallback='https://api.scryfall.com')
        self.search_endpoint = config.get('search_endpoint', fallback='/cards/search')
        self.header_accept = config.get('header_accept', fallback='application/json')
        self.header_user_agent = config.get('header_user_agent', fallback='MoritzHayden/momir-basic-printer')
        self.request_delay = config.getfloat('request_delay', fallback=0.1)
        self.query = config.get('query', fallback='t%3Acreature+cmc%3A')
        self.unique = config.get('unique', fallback='cards')
        self.order = config.get('order', fallback='name')
        self.dir = config.get('dir', fallback='asc')
        self.include_extras = config.getboolean('include_extras', fallback=False)
        self.include_multilingual = config.getboolean('include_multilingual', fallback=False)
        self.include_variations = config.getboolean('include_variations', fallback=False)
        self.page = config.getint('page', fallback=0)
        self.format = config.get('format', fallback='json')
        self.pretty = config.getboolean('pretty', fallback=False)
